# Generated by Django 4.2.8 on 2026-05-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='adress',
            new_name='address',
        ),
    ]
